on: [push]
name: Azure Infrastructure
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        uses: azure/arm-deploy@1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          #resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./infrastructure/resources/rg.bicep
          parameters: name=rg-badadvisor-dev location=centralus
          failOnStdErr: false
